microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaiuvgenerator
    tag: "0.0.1-17" #improve
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 80
  ingress:
    create: true
    host: "weudev.shared.internal.dev.platform.pagopa.it"
    path: /pagopa-iuv-generator-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: '70'
  envConfig:
    FUNCTIONS_WORKER_RUNTIME: "java"
    IUV_STORAGE_TABLE: "iuvstable"
    IUV_MAX_RETRY_COUNT: "1"
    WEBSITE_SITE_NAME: "pagopaiuvgenerator" # required to show cloud role name in application insights
  envSecret:
    IUV_STORAGE_CONNECTION_STRING: iuv-generator-cosmos-primary-connection-string
    APPLICATIONINSIGHTS_CONNECTION_STRING: ai-d-connection-string
  keyvault:
    name: "pagopa-d-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
